### ISSUE TITLE
Imresize not working

### ISSUE THREAD

**Issue by joshuayuny** [CSAILVision/IBD#3]
Hi,
I was wondering has anyone gotten this issue with imresize when running the command python3 test.py? In addition I tried installing Pillow and installing these other commands:
pip install numpy
pip install scipy
pip install matplotlib
pip install Pillow

But it hasn't been able to fix it.

Here's the error I get.

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from loader.model_loader import loadmodel
  File "/home/joshuayun/Desktop/IBD/loader/model_loader.py", line 5, in <module>
    from util.feature_operation import hook_feature, hook_grad
  File "/home/joshuayun/Desktop/IBD/util/feature_operation.py", line 6, in <module>
    from scipy.misc import imresize, imread, imsave
ImportError: cannot import name 'imresize'

Any help would be great. Thanks

**Comment by sunyiyou** [comment]
That's the problem of your scipy environment. Make sure it is working first.

**Comment by joshuayuny** [comment]
Okay. I was able to fix that.
